### ISSUE TITLE
Contributor License Agreements 에러가 납니다.

### ISSUE THREAD

**Issue by cshwan78** [17-1-SKKU-OSS/angular-ko#7]
![image](https://cloud.githubusercontent.com/assets/13327016/26579339/4e3c7f18-456e-11e7-9253-f16841e24298.png)

https://github.com/angular/angular-ko/pull/54

**Comment by bluecri** [comment]
CLA에 깃허브 아이디와 이메일을 등록해야 합니다. 제 경우 등록후 시도해보았는데 여전히 인증이 불가능한 상태입니다.
![image](https://cloud.githubusercontent.com/assets/21999493/26580721/5309b24e-4574-11e7-8e02-353e6017b6c3.png)
angular-ko의 다른 commit을 확인해 보았는데 CLA인증이 없어도 merge하시는 분이 이에 상관없이 코드 확인 후 merge 승인을 하는 경우가 있어서 큰 문제는 안될것 같습니다.

**Comment by bluecri** [comment]
CLA 관련 설명 wiki에 추가하였습니다.

**Comment by cshwan78** [comment]
1.
